version: '3'
    
services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000 &&
             python seeder.py"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
